### PR TITLE
add extensionConfigs to snapShot

### PR DESCRIPTION
**Pull request by Xunzhuo**
1. add extensionConfigs to snapShot

### CODE REVIEW

**Review by alecholmez — APPROVED** [review]
Great thank you for this, can you rebase/squash your commits? We can merge after that

**Comment by Xunzhuo** [comment]
@alecholmez  Sure I will rebase these commit~

**Comment by Xunzhuo** [comment]
@alecholmez  I think it`s OK to merge now~😀

**Review by alecholmez — APPROVED** [review]
Thanks for this!

**Comment by Xunzhuo** [comment]
@alecholmez  my pleasure~ 😊

**Pull request merged**
