### PR TITLE
add SDS support

### PR DESCRIPTION
**Pull request by kyessenov**
Pending on SDS client implementation.

Contributes to #57 

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by taion809** [comment]
@kyessenov hows this going?  I see there were some updates to this story here: https://github.com/envoyproxy/envoy/issues/1194

**Comment by kyessenov** [comment]
I put it on hold until SDS got merged into envoy. Seems like it finally did. I'll finish it up tomorrow most likely.

**Comment by wozz** [comment]
Is there any update on this? I was able to get this working with envoy 1.8.0 in a local test by just merging this branch into master and using a very basic xds server implementation.

**Comment by kyessenov** [comment]
I'll complete and merge it today. Sorry, fell out of my list, and SDS took some time to land in envoy.

**Comment by kyessenov** [comment]
Coverage drop is expected: it's a bit more work to stub out TLS secrets. Should remain as a TODO.

**Comment by kyessenov** [comment]
@taion809 Adding a TODO to the linked issue.

**Pull request merged**
