### PR TITLE
api: add custom buffer size for ADS, docs

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by fxposter** [comment]
I was thinking about that. Let's do `WithBufferSize(xdsSize, adsSize int)` to try to adopt cases where xds would require additional buffer if using custom caches that delay cancel() calls?

**Comment by fxposter** [comment]
And set defaults to 1 for xds and 8 for ads

**Comment by kyessenov** [comment]
Sure. I'm waiting if anyone reports an issue with the previously merged change in case we have to revert. If all is good, let's move on with this and other changes.

**Review by jyotimahapatra — APPROVED** [review]
Thanks for the change! lgtm.

**Comment by jyotimahapatra** [comment]
I am still in the process of pulling the changes since the e2e tests are failing. I will report back when i have it pulled into our infra.

**Comment by fxposter** [comment]
LGTM too

**Comment by kyessenov** [comment]
@jyotimahapatra LMK if there is any issue with the latest changes. Otherwise, I think it's time to merge.

**Comment by jyotimahapatra** [comment]
@kyessenov im currently bringing in gcp update into xdsrelay https://github.com/envoyproxy/xds-relay/pull/181
We should merge this PR irrespective of my effort.

**Pull request merged**
