### PR TITLE
Add basic golangci-lint integration.

### PR DESCRIPTION
**Pull request by jpeach**
Add a "lint" target to the build that runs golangci-lint. This needs to
be run manually for now. CI can be wired up later once the issues are
fixed and there is consensus on the set of linters to run.

This updates #414.

Signed-off-by: James Peach <jpeach@apache.org>

### CODE REVIEW

**Comment by alecholmez** [comment]
@mattklein123 You might want to take a quick look at this since you reworked the CI

**Comment by alecholmez** [comment]
I think excluding these:
```
issues:
  exclude:
  exclude-rules:
  - text: "SA1019: package github.com/golang/protobuf/jsonpb is deprecated"
    linters:
    - staticcheck
  - text: "SA1019: package github.com/golang/protobuf/proto is deprecated"
    linters:
    - staticcheck
  - text: "SA1019: proto.MessageName is deprecated"
    linters:
    - staticcheck
```
might not be what we want. We might as well fix them if at all possible

**Comment by jpeach** [comment]
> might not be what we want. We might as well fix them if at all possible. 

Migrating to the new proto API has effects on downstream consumers and I suspect is probably worth a separate discussion.

> I know we copy around a lock quite a lot in the SOTW code so that should also reduce the lint issues a bit

Yeh that gets picked up. Not fixed here yet.

**Comment by jpeach** [comment]
Fixed the remaining lint issues. I'll rebase and squash before marking this ready.

**Comment by jpeach** [comment]
Closing in favor of #455 because I messed up the branching in my fork :-/

**Pull request closed without merging**
