### PR TITLE
Fix gogo-genproto dependency

### PR DESCRIPTION
**Pull request by rshriram**
use istio.io/gogo-genproto instead of github.com/istio/gogo-genproto, as the current form is preventing the use of this library in istio code base.

### CODE REVIEW

**Comment by rshriram** [comment]
@9len I believe it should work in the same way (istio or non istio), if you are using dep/glide. We have made sure that istio.io/gogo-genproto is accessible for all the go tools (all our go packages are rooted at istio.io). @douglas-reid might be able to provide more go expertise here.

**Comment by kyessenov** [comment]
Thanks for fixing this. Did not realize the vanity URL was mandatory :)

**Comment by kyessenov** [comment]
@9len there is no dependency on istio, we use `istio.io` as a placeholder for Google APIs (which are brought in by gRPC services) until the official googleapis packages support gogo (per @wora).

**Comment by gnirodi** [comment]
Thanks guys for pushing this through.

**Comment by 9len** [comment]
Thanks. Misread the diff, I understand now.

**Pull request merged**
