### PR TITLE
update data-plane-api dependency to e3bcabae8359ab399273f4295d1318179123c1fe

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
Fixes https://github.com/envoyproxy/envoy/issues/5269.

### CODE REVIEW

**Comment by vadimeisenbergibm** [comment]
@lizan Could you please review and approve this PR?

**Comment by lizan** [comment]
There are a couple of PR to bump data-plane-api, anyone of @envoyproxy/go-control-plane can take a look?

**Comment by ggreenway** [comment]
@vadimeisenbergibm Do you know why "v2" was added before a bunch of imports that already ended in "v2"? Was that done by the update tool? Was that needed to fix the CI build?

**Comment by vadimeisenbergibm** [comment]
Thanks @ggreenway !

**Comment by vadimeisenbergibm** [comment]
@ggreenway Could you please add version tags to the commits? v0.6.4 and v0.6.5?

**Comment by vadimeisenbergibm** [comment]
@mattklein123 May I ask you a favor - could you please add version tags to the latest commits to go-control-plane? I guess v0.6.4 and v0.6.5. Everybody is probably on vacation right now, I do not know what is the process to add version tags. Istio cannot be updated to the latest proxy SHA without updating the dependency on go-control-plane, I opened an issue here - https://github.com/envoyproxy/envoy/issues/5269.

**Comment by mattklein123** [comment]
@vadimeisenbergibm sorry I don't know anything about this. Who normally does this?

**Comment by dio** [comment]
@vadimeisenbergibm I have added two tags, see if that helps.

**Comment by dio** [comment]
And I think we need to have a point release that is in-sync with envoy 1.9.0. Will do that if no objections.

**Comment by vadimeisenbergibm** [comment]
@dio Great, thanks!

**Comment by ggreenway** [comment]
@vadimeisenbergibm Can you create a PR to the README documenting why the tags are important, and when tags should be generated?

**Pull request merged**
