### PR TITLE
bug: fix possible panic if no cache logger is supplied

### PR DESCRIPTION
**Pull request by alecholmez**
Signed-off-by: Alec Holmes <alecholmez@me.com>

### CODE REVIEW

**Review by snowp — APPROVED** [review]
Thanks, LG

Anything we can do to make this less risky in the future? Be that adding tests that cover this or improve the API?

**Comment by alecholmez** [comment]
@snowp I think both honestly, It might be worth changing the API so if a logger isn't declared at start we can have a default, that way we don't need to check for nil logs everywhere

**Comment by alecholmez** [comment]
sorry @snowp had to rebase, can you rereview?

**Review by snowp — APPROVED** [review]
LG. Are you planning on tackling the null logger or should I do that?

**Comment by alecholmez** [comment]
I'll go ahead and do that, should be simple

**Pull request merged**
