### PR TITLE
server api without linearization

### PR DESCRIPTION
**Pull request by fxposter**
@jyotimahapatra @kyessenov Followup of #375 

Do you envision this to have any problems for clients to migrate to? Let's put linearization aside for now.

### CODE REVIEW

**Comment by kyessenov** [comment]
@fxposter @jyotimahapatra I think the path forward is to test small changes like this in xds-relay staging, and try to instrument code if something goes wrong again.

**Comment by jyotimahapatra** [comment]
`I think the path forward is to test small changes like this in xds-relay staging, and try to instrument code if something goes wrong again.` I can try out any experimental changes our staging environment.

**Comment by fxposter** [comment]
@jyotimahapatra do you use type urls not from this list for xds-relay: https://github.com/envoyproxy/go-control-plane/blob/master/pkg/resource/v2/resource.go#L16-L21 ?

**Comment by fxposter** [comment]
Also - do you use v2 or v3?

**Comment by jyotimahapatra** [comment]
We use eds/cds/lds/rds . We only use v3

**Comment by kyessenov** [comment]
@fxposter can you fix create_version? once it passes CI, I guess we can try it in staging.

**Comment by fxposter** [comment]
@kyessenov I thought a bit about why previous attempt could lead to system being overloaded and I think that https://github.com/envoyproxy/go-control-plane/pull/357/files#diff-d8ad87612eeb084487962f9097b132371b1cb8402432bc8ea190ab973fdba1feR223 - here we should do a slightly modified `processAll` - instead of sending all ready responses, we should send all but from the one that has the type equal to request that we just got - this is not exactly matching the behaviour that currently exists, but closer than just doing `processAll`.

**Comment by fxposter** [comment]
@jyotimahapatra can you, please, take a look?

**Comment by fxposter** [comment]
@jyotimahapatra @kyessenov Guys, can we finally proceed, please?

**Comment by kyessenov** [comment]
I'd ping @jyotimahapatra or @jessicayuen how to get it tested on lyft's infrastructure. The code was fine to me, but I imagine the real tests are in the staging.

**Comment by jessicayuen** [comment]
Jyoti is no longer at Lyft, I'll take a look at this today or tomorrow.

**Comment by fxposter** [comment]
huh. lucky me that @kyessenov has another person to ping :)

**Comment by jessicayuen** [comment]
@samrabelachew pulled this change into xds-relay / Lyft and has been graciously testing on our staging traffic. So far things look promising, but we'd like to bake this over the weekend. If things look good, happy to approve and merge this!

**Comment by jessicayuen** [comment]
@fxposter We tested this internally and didn't see any problems. Notice this PR is still marked WIP, is that still the case?

**Comment by fxposter** [comment]
@jessicayuen nope, I just forgot to remove WIP after generating v3 version/etc.

**Review by jessicayuen — APPROVED** [review]
Thanks, this LGTM.

**Comment by jessicayuen** [comment]
@kyessenov Did you want to take a pass before I merge this?

**Comment by fxposter** [comment]
@snowp wow, merging incremental interfaces was fast. Should we maybe align them with the new way of what I propose here?

**Comment by fxposter** [comment]
@kyessenov rebased on top of current upstream

**Comment by snowp** [comment]
@fxposter Sorry I wasn't aware that we wanted to apply this to the Delta API as well, I was just trying to fast track the Delta work since it'd been stalled for so long. 

I don't feel particularly strongly about whether to land Delta as-is and make these interfaces updates later or to try to update it to use this asap, let's see what @alecholmez thinks since he's doing the work.

**Comment by alecholmez** [comment]
@fxposter @snowp I'm not opposed to bringing these changes back into the implementatins. I'm about to open the PR for the simple snapshot cache implementation so I can just roll these changes back in there. @fxposter do you want to merge this and then I pull in the changes to delta?

**Comment by jessicayuen** [comment]
@fxposter can you merge in the changes and we'll get this in?

**Pull request closed without merging**
