### PR TITLE
Add detailed_metric field to ratelimit descriptor

### PR DESCRIPTION
**Pull request by akondapuram**
I created an [issue ](https://github.com/envoyproxy/ratelimit/issues/461)with regard to adding detailed_metric support for dynamic ratelimiting using xds server a few weeks ago.
This is the first PR to address the same. Once this is merged, will add necessary changes to the [ratelimit repo](https://github.com/envoyproxy/ratelimit) and create a new PR.  Here is the [draft PR](https://github.com/envoyproxy/ratelimit/pull/465).

### CODE REVIEW

**Comment by valerian-roche** [comment]
Hey, can you clarify why this should be generated prior to the protobuf files being merged? It seems counter-intuitive to not allow users to regenerate based on the merged proto files

**Comment by ramaraochavali** [comment]
@phlax @kyessenov Can you please take a look?

**Comment by akondapuram** [comment]
> Hey, can you clarify why this should be generated prior to the protobuf files being merged? It seems counter-intuitive to not allow users to regenerate based on the merged proto files

@valerian-roche 
Hi Valerian, thank you for looking into this PR. 

From what I saw before from the conversation on the [go-control-plane PR](https://github.com/envoyproxy/go-control-plane/pull/598/), the changes first were made on the go-control-plane repo. Please see the following two PRs.
1. [This PR](https://github.com/envoyproxy/go-control-plane/pull/598/files) was checked-in to go-control-plane  on Jan 27th.
2. The [second PR](https://github.com/envoyproxy/ratelimit/pull/373) to the ratelimit repo was then checked in on Feb 7th.
Hence I created the first PR first (I generated it using the rls_conf.proto) and added the ratelimit [PR draft ](https://github.com/envoyproxy/ratelimit/pull/465)as a reference in the this PR.

Also, the second PR can’t be merged in totality until the pb.go files are merged on the control plane side. Because there are several files (such as resource.go, config_xds.go) that depend on the [rls_conf.pb.go](https://github.com/envoyproxy/go-control-plane/blob/main/ratelimit/config/ratelimit/v3/rls_conf.pb.go) file. 

However, if you think the proto file has to be checked-in first on the ratelimit repo, I can split up this[ draft PR](https://github.com/envoyproxy/ratelimit/pull/465). I can first check-in the proto files to ratelimit repo, then check-in the generated file to go-control-plane repo and once this is merged, I can make the other changes in a separate PR. Please let me know your thoughts. Thank you! 

@renuka-fernando Tagging you here for your thoughts/review as well, as you have contributed the dynamic ratelimiting feature to both the repos. Thanks!

**Comment by renuka-fernando** [comment]
I guess this complexity is because we couldn't automate generating pb files as discussed in this issue https://github.com/envoyproxy/go-control-plane/issues/646.

@phlax, @jpeach, @dio, @arkodg could you please have a look?

**Comment by ramaraochavali** [comment]
@alecholmez Can you please review this PR?

**Review by valerian-roche — APPROVED** [review]

**Comment by akondapuram** [comment]
Thank you for your approval @valerian-roche Appreciate it.

**Comment by ramaraochavali** [comment]
@envoyproxy/go-control-plane Could you please help merge this?

**Comment by ramaraochavali** [comment]
@alecholmez Can you please help creating a release with this commit so that it can be used in gRLS service?

**Pull request merged**
