### PR TITLE
cache: clean up TTL logic after v2 removal

### PR DESCRIPTION
**Pull request by snowp**
Now that V2 has been removed, we can clean up a lot of the awkward handling of TTL
that was required due to the fields not existing in V2.

Signed-off-by: Snow Pettersen <snowp@lyft.com>

### CODE REVIEW

**Review by alecholmez — APPROVED** [review]
This is cool, I wonder if this will help TTL in incremental as well. Less things to worry about

**Comment by snowp** [comment]
Should make it a little bit easier and also a lot clearer what's actually going on

**Comment by alecholmez** [comment]
Sounds good to me 😄 this looks great. Though I can't approve for merge haha. Maybe @jessicayuen can?

**Comment by alecholmez** [comment]
@snowp wanna merge this?

**Pull request merged**
