### PR TITLE
Mirrored from envoyproxy/envoy @ e3247539bcc39f3111287b479a85e51655a6…

### PR DESCRIPTION
**Pull request by kyessenov**
…f1db

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by incfly** [comment]
This one has the changes that we need. @rshriram @GregHanson . We just need to wait this PR to be merged.

**Comment by incfly** [comment]
https://github.com/envoyproxy/go-control-plane/pull/232/files#diff-95da37825bf8533465f05b327805ab91R675

**Comment by kyessenov** [comment]
@htuch Can we please activate the mirroring job? We need some admin job to push these things without review.

**Comment by htuch** [comment]
@kyessenov I'll take an AI to restore the mirroring. Need a fresh public-private key pair and to rollback the rollback with this change.

**Pull request merged**
