### PR TITLE
Option for the delta server to override the channel capacity and avoid deadlocks

### PR DESCRIPTION
**Pull request by lobkovilya**
Please check the context at https://github.com/envoyproxy/go-control-plane/issues/875.

This is quite a naive and straightforward way to solve it, but it'd work perfectly fine for us. Please let me know your thoughts, I'm happy to discuss a better solution.

### CODE REVIEW

**Comment by valerian-roche** [comment]
Hey 👋, I do believe it would solve this issue, but this raises concerns in my opinion with leaking too many internals of the server implementation. It would be very brittle to require users to set this, especially if it does not fail at startup but only in some edge cases. We might be able to do it in a more efficient way based on the current number of distinct opened watches in the given stream, or by using the old model when watches do not watch the resources with an ADS order requirement.

**Comment by lobkovilya** [comment]
Hey @valerian-roche! Yeah, I agree, that the solution is far from ideal. 

> We might be able to do it in a more efficient way based on the current number of distinct opened watches in the given stream, or by using the old model when watches do not watch the resources with an ADS order requirement.

Do you know if something like that is already in progress or planned?

**Comment by valerian-roche** [comment]
Hey, there is no ongoing work on the issue, but I may be able to take a stab at it soon.

**Comment by lobkovilya** [comment]
Hey @valerian-roche, I'd like to take on this issue as we're blocked right now with `go-control-plane` upgrades. Could you please elaborate on the idea you mentioned here:
> We might be able to do it in a more efficient way based on the current number of distinct opened watches in the given stream

**Comment by lukidzi** [comment]
Hi @valerian-roche,

Is it possible to include this simple fix, considering there are no other ongoing changes? This modification doesn't alter the current user behavior, as the default value remains the same, but it allows users to provide a custom size. Since there has been no progress on this issue and the change does not break anything, could we consider incorporating it into the codebase?

**Comment by valerian-roche** [comment]
Hey, I'd like to not merge this. This is far more likely to create deadlocks for users if they are not correct with the value, and would be forever part of the public API. I'd much rather we address the core problem of this sized channel

**Pull request closed without merging**
