### PR TITLE
Update data plane to 3cb3571f093602b7d6a06945906802666febcf66

### PR DESCRIPTION
**Pull request by brian-avery**

### CODE REVIEW

**Comment by brian-avery** [comment]
@kyessenov Can you please take a look at this?

**Comment by kyessenov** [comment]
Can you try to run `make format`?

**Comment by kyessenov** [comment]
CI still complains about `make check` failing... It might be related to inconsistent versions of goimports. Can you look into that?

**Comment by brian-avery** [comment]
@kyessenov thanks. I'll see what I can find.

**Comment by brian-avery** [comment]
Thanks @kyessenov running format in the circleci image fixed it. Must be different versions or something.

**Pull request merged**
