### PR TITLE
Update data-plane-api to SHA f01638479cf6dbb246dd6fa3582f169c35460891

### PR DESCRIPTION
**Pull request by venilnoronha**
Istio currently [depends](https://github.com/istio/istio/blob/d28eb4d2ed4d07f06816169d6217efc79082002e/Gopkg.toml#L112) on the `revert_grpc_version_update` branch of this repository. Therefore, this PR applies the `data-plane-api` SHA update to the `revert_grpc_version_update` branch.

Signed-off-by: Venil Noronha <veniln@vmware.com>

### CODE REVIEW

**Comment by venilnoronha** [comment]
@davecheney done.

**Comment by davecheney** [comment]
ok, thanks for explaining. I didn't understand that this was not a PR on the master branch.

**Comment by venilnoronha** [comment]
The `data-plane-api` has been updated on the `master` branch in 676016db8193d83324a507a986a78cd3642ad713.

**Comment by rshriram** [comment]
@kyessenov updated the gRPC version in the go control plane and unfortunately its not compatible with rest of Istio (seems it requires more changes across the board). And he did that right around the release time. So, instead of reverting that change for all consumers, I created a branch without those changes. 

In the long run though, we need to resolve it in Istio. So, @kyessenov its on you to fix up the Istio gRPC stuff as well. :) ..
@venilnoronha please submit the PR to master branch. We shouldn't be taking in anything to this branch

**Comment by kyessenov** [comment]
Sorry, I was not expecting last minute envoy API changes to be shipped in istio.
Istio needs to get off gRPC 1.11, which is very old by this time. @douglas-reid had a PR to update istio, but it appears to be a monumental effort.

**Comment by venilnoronha** [comment]
Closing as `go-control-plane` was switched to `^0.5.0` in istio/istio#8036.

**Pull request closed without merging**
