### PR TITLE
use replace in examples and xdsmatcher

### PR DESCRIPTION
**Pull request by mmorel-35**
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

### CODE REVIEW

**Comment by phlax** [comment]
can you give some explanation of change (apologies if its obvious)

**Comment by mmorel-35** [comment]
go.mod requires pined versions.
When there are multiples modules on a repository that are interdependant, the use of replace allows to use the up to date version of the local modules in the go.mod file.

**Comment by phlax** [comment]
thnks for explanation - i have seen it used in Envoy and wasnt 100% clear about what it did

**Comment by phlax** [comment]
> Why was it not merged ?

fell through the cracks i think

> Shall I reopen this ?

yep

**Pull request closed without merging**
